### ISSUE TITLE
Confusion about versions

### ISSUE THREAD

**Issue by benilton** [rocker-org/hadleyverse#10]
Hi everyone,

I apologize for the naive question (just starting with Docker), but my understanding is that I should use

```
FROM rocker/hadleyverse:3.3.2
```

to get R 3.3.2.

However, when I run

```
docker run -p 8787:8787 -ti benilton/bioinformatics
```

RStudio uses R 3.1.1.

If I run

```
docker run -ti benilton/bioinformatics R
```

I get R 3.3.2.

I wonder if you guys could point me to the proper way to get RStudio using R 3.3.2?

Thank you very much, benilton

**Comment by cboettig** [comment]
What you are doing should work, but it's impossible to debug with the information you have provided.  You should first confirm that running `rocker/hadleyverse:3.3.2` with RStudio gets you the correct version.  

Please make sure your machine has the most recent version of `rocker/hadleyverse:3.3.2` by running `docker pull`.  

Better yet, it would be good if https://hub.docker.com/r/benilton/bioinformatics/ used the 'automated build' rather than just pushing a binary image.  That ensures it uses the correct version and lets other see the Dockerfile you are using.  

As an aside, we're encouraging users to switch to `rocker/tidyverse` instead of `hadleyverse`.  I've updated the README to indicate this.

**Comment by benilton** [comment]
@cboettig , many thanks for your help. I'm now able to identify that the problem I have is caused by something else! Not bad for Day 1. I hope to be able to work on the automated builds soon!
